name:                six-degrees-of-wikipedia
version:             0.1.0.0
github:              "ryanwee1001/six-degrees-of-wikipedia"
license:             BSD-3-Clause
author:              "Blake Appleby, Jonathan Hall, Ryan Wee"
maintainer:          "aba2176, jah2328, rw2800@columbia.edu"
copyright:           "2023 Blake Appleby, Jonathan Hall, Ryan Wee"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ryanwee1001/six-degrees-of-wikipedia/blob/main/README.md>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - aeson
  - binary
  - bytestring
  - containers
  - monad-par
  - split

executables:
  parallel-bfs:
    main:                parallel-bfs.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    dependencies:
    - monad-par
    - six-degrees-of-wikipedia

tests:
  # parallel-bfs-test:
  #   main:                parallel-bfs-test.hs
  #   source-dirs:         test
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - six-degrees-of-wikipedia
  json-parse-test:
    main:                json-parse-test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - six-degrees-of-wikipedia
    - aeson
